nombre: Buscalo
version: 2.1
modo_ejecucion: Desarrollo
puerto: 2712 

database:
 nombre: Mi base
 usuario: Daniel
 contrase√±a: daniel2007

tiempo_espera:
 conexion: 30546
 solicitud: 233566

 color: "Gris"

